AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - bin/**/*
    - spec/dummy/bin/**/*
    - spec/dummy/db/migrate/*
    - spec/dummy/db/schema.rb


  DisplayCopNames: true

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false


Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentHash:
  EnforcedStyle: 'consistent'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Metrics/LineLength:
  Enabled: false

Metrics/LineLength:
  Max: 128
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - spec/dummy/config/**/*
    - spec/dummy/Rakefile
    - spec/lib/**/*
  

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/lib/**/*
    - spec/controllers/**/*
    - dynamic_scaffold.gemspec

Metrics/MethodLength:
  Max: 20

Rails/HttpPositionalArguments:
  Exclude:
    - "spec/dummy/config/routes.rb"

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Metrics/ModuleLength:
  Max: 120

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/dummy/app/controllers/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver